version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: calendar-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - app-network

  calendar-backend:
    image: bboycasper128/calendar-backend:latest
    container_name: calendar-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DB_CNN=mongodb://root:example@mongo:27017/calendar-db?authSource=admin
      - SECRET_JWT_SEED=Esto-Es-UnA-Palbr@_SecretA1234567
    depends_on:
      - mongo
    restart: always
    networks:
      - app-network

  calendar-frontend:
    image: bboycasper128/calendar-frontend:latest
    container_name: calendar-frontend
    args:
        VITE_API_URL: "http://calendar-backend:4000"
    ports:
      - "3000:80"
    depends_on:
      - calendar-backend
    restart: always
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
